### ISSUE TITLE
Shopify says variant PLU-0000014 exists with same attributes error when trying to sync an order with PLU-0000014 on it

### ISSUE THREAD

**Issue by prices** [frappe/ecommerce_integrations#174]
**What I get:**
```
Traceback (most recent call last):
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 46, in sync_sales_order
    create_items_if_not_exist(order)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 307, in create_items_if_not_exist
    product.sync_product()
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/connection.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 57, in sync_product
    self._make_item(product_dict)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 68, in _make_item
    self._create_item_variants(product_dict, warehouse, attributes)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 179, in _create_item_variants
    self._create_item(shopify_item_variant, warehouse, 0, attributes, template_item.name)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 144, in _create_item
    ecommerce_item.create_ecommerce_item(
  File "apps/ecommerce_integrations/ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py", line 159, in create_ecommerce_item
    new_item.insert(ignore_permissions=True, ignore_mandatory=True)
  File "apps/frappe/frappe/model/document.py", line 240, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 971, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 869, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1161, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1144, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 863, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 116, in validate
    self.validate_variant_attributes()
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 726, in validate_variant_attributes
    frappe.throw(_("Item variant {0} exists with same attributes")
  File "apps/frappe/frappe/__init__.py", line 445, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 424, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 378, in _raise_exception
    raise raise_exception(msg)
erpnext.controllers.item_variant.ItemVariantExistsError: Item variant PLU-0000014 exists with same attributes
```

**What I expect:**

I expect it to sync the order, since the part it is complaining about already exists (PLU-0000014).  The shopify connector even originally created this item.

Even if I rename the original item it gives me the same error.  I can't delete the original item because it has stock transactions against it.

**What I would like to see:**
1. I would like to see a way to say "use X item as PLU-0000014"
2. or have it just use the item it says is in the way.

**Comment by prices** [comment]
I am now noticing that of the two orders that are doing this, one is for PLU-0000013 and one is for PLU-0000014.  Both are variants of the same item, and have different shopify variant_id numbers.

**Comment by prices** [comment]
Let me know if there is any more debugging information you need or things you would like me to try.

**Comment by prices** [comment]
Sorry, I am on the latest V13 of erpnext and the latest of ecommerce_integrations.

**Comment by prices** [comment]
This seems to be the problem.  It is returning false, even though the item exists.  I am going to dig further.
```
def _is_sku_synced(integration: str, sku: str) -> bool:
	filter = {"integration": integration, "sku": sku}
	return bool(frappe.db.exists("Ecommerce Item", filter))
```

**Comment by prices** [comment]
I ended up manually editing the database to fix this.  I had to set the sku manually.
