### ISSUE TITLE
Shopify has stopped support for API Version `2021-04`

### ISSUE THREAD

**Issue by pruthvi145** [frappe/ecommerce_integrations#179]
## Traceback

```bash
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/shopify/api_version.py", line 17, in coerce_to_version
    return cls.versions[version]
KeyError: '2021-04'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 46, in sync_sales_order
    create_items_if_not_exist(order)
    File "apps/ecommerce_integrations/ecommerce_integrations/shopify/connection.py", line 34, in wrapper
    with Session.temp(*auth_details):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "env/lib/python3.8/site-packages/shopify/session.py", line 37, in temp
    original_session = shopify.Session(original_domain, original_version, original_token)
  File "env/lib/python3.8/site-packages/shopify/session.py", line 47, in __init__
    self.version = ApiVersion.coerce_to_version(version)
  File "env/lib/python3.8/site-packages/shopify/api_version.py", line 19, in coerce_to_version
    raise VersionNotFoundError
shopify.api_version.VersionNotFoundError
```

## Update

As per my research, Shopify still supports the version `2021-04` (It will be stopped soon as per  [release-schedule](https://shopify.dev/api/usage/versioning#release-schedule)).

However, the current problem is with `ShopifyAPI` version. In version `8.2.0` it was checking version dynamically which was [fixed](https://github.com/Shopify/shopify_python_api/pull/495) in version `8.4.0`.

If we update the version of `ShopifyAPI` to 8.4.0 or later, it should work as expected because as per latest version (`10.0.0`) of `ShopifyAPI`,`2021-04` is still [supported](https://github.com/Shopify/shopify_python_api/blob/b9d89e7a2157b7dc9eaa768dca1c508ff54d3a2c/shopify/api_version.py#L32). But we can not bump the version from `8.2.0` to `8.4.0 or later` because it has conflicts with frappe for [PyJWT](https://github.com/frappe/ecommerce_integrations/blob/e70e586c6526251fefbd58bc3e83e41f9d98b2b9/requirements.txt#L1).

PyJWT conflict is already solved on [develop](https://github.com/frappe/frappe/commit/165ff8e1bfe1a8e94b9995626ea5dd188b2e23f2) but is there any plan to backport it to version-13?

**Comment by prices** [comment]
I had to uninstall this just to get other stuff done.  It was blocking everything we tried to do.  Please fix this soon, as I really need this to keep in sync with shopify.  I really don't want to do it manually.
