### ISSUE TITLE
Exception: Account None not found - while saving shopify order

### ISSUE THREAD

**Issue by Karpuraraj** [frappe/ecommerce_integrations#208]
**Error from API:**
{
    "exc_type": "DoesNotExistError",
    "_server_messages": "[\"{\\\"message\\\": \\\"Item Price added for 7274795008181 in Price List Ecommerce Integrations - Ignore\\\", \\\"title\\\": \\\"Message\\\", \\\"alert\\\": 1}\", \"{\\\"message\\\": \\\"Account None not found\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1}\"]"
}

I checked in debugging mode this error occuring from **create_sales_invoice(order, setting, so)** function. Could you please help?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 1261, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 1243, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "/home/essplor/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 118, in validate
    self.validate_income_account()
  File "/home/essplor/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 213, in validate_income_account
    validate_account_head(item.idx, item.income_account, self.company, "Income")
  File "/home/essplor/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 1951, in validate_account_head
    account_company = frappe.get_cached_value("Account", account, "company")
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 1044, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 1020, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 1074, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 79, in get_doc
    return controller(*args, **kwargs)
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 118, in __init__
    self.load_from_db()
  File "/home/essplor/frappe-bench/apps/frappe/frappe/model/document.py", line 163, in load_from_db
    frappe.throw(
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/essplor/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Account None not found

**Comment by Karpuraraj** [comment]
I solved this by filling out “Default Income Account” field in the company i set up.
