### ISSUE TITLE
No module named 'ecommerce_integration' 

### ISSUE THREAD

**Issue by amet123** [frappe/ecommerce_integrations#236]
Could not find app "ecommerce_integration":
No module named 'ecommerce_integration'
An error occurred while installing ecommerce_integration: No module named 'ecommerce_integration'
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -3073059119516583188

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 262, in install_app
    app_hooks = frappe.get_hooks(app_name=name)
  File "apps/frappe/frappe/__init__.py", line 1493, in get_hooks
    hooks = _dict(_load_app_hooks(app_name))
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1465, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ecommerce_integration'

**Comment by ravibharathi656** [comment]
Hi,

It seems the issue is due to the `ecommerce_integration` app not being found. Please check if the app is installed in your bench. If it's not installed, try installing it first and then run a site migration.

Let me know if the issue persists after that.

Thank you,
Ravibharathi
