### ISSUE TITLE
Issue getting products from Shopify.

### ISSUE THREAD

**Issue by shadmeoli** [frappe/ecommerce_integrations#309]
I am getting an issue getting product from shopify.

### App Versions
```
{
	"builder": "1.4.0",
	"doppio": "0.0.1",
	"ecommerce_integrations": "1.17.0",
	"erpnext": "15.13.0",
	"frappe": "15.13.0",
	"hrms": "16.0.0-dev",
	"raven": "1.3.2",
	"studio_dashboard": "0.0.1",
	"vendor": "0.0.1"
}
```
### Route
```
shopify-import-products
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.py", line 19, in get_shopify_products
    shopify_products = fetch_all_products(from_)
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_products.py", line 30, in fetch_all_products
    for product in collection:
TypeError: 'NoneType' object is not iterable

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"from_": null
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/ecommerce_integrations.shopify.page.shopify_import_products.shopify_import_products.get_shopify_products",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'NoneType' object is not iterable",
	"exc_type": "TypeError",
	"_exc_source": "ecommerce_integrations (app)"
}
```

When I use the credentials I used to connect to shopify separately I am getting the products.

**Comment by Karuppasamy923** [comment]
Hi @shadmeoli ,

Could you please verify whether the scope shown in the image below has been enabled under the Admin API access scopes section of your Shopify store’s app settings? This specific scope is required to manage product updates.

![Image](https://github.com/user-attachments/assets/c43e8b7f-323b-4c97-8046-dac3da25c492)

Additionally, please confirm whether products are currently available in your Shopify account.

If you are using Frappe Cloud, kindly raise a support ticket so we can review the error logs in your instance. Once done, please share the ticket ID here.

Kindly share the ticket ID here
