### ISSUE TITLE
Cannot get any sync or connection to Shopify 

### ISSUE THREAD

**Issue by yasqueentyler** [frappe/ecommerce_integrations#327]
I cannot get my frappe cloud instance of erpnext to sync anything with my Shopify. I cannot even save the settings because it says it can find the webhopks JSON or something.  Below is the error information from the app: 
# App Versions

```

{

"chat": "0.0.1",

"crm": "1.19.0",

"ecommerce_integrations": "1.20.1",

"email_delivery_service": "0.0.1",

"erpnext": "15.32.0",

"frappe": "15.37.0",

"helpdesk": "0.10.0",

"hrms": "15.25.2",

"payments": "0.0.1",

"raven": "1.6.5"

}

```

### Route

```

Form/Shopify Setting/Shopify Setting

```

### Traceback

```

Traceback (most recent call last):

File "apps/frappe/frappe/[app.py](http://app.py/)", line 114, in application

response = frappe.api.handle(request)

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/api/__init__.py", line 49, in handle

data = endpoint(**arguments)

^^^^^^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/api/[v1.py](http://v1.py/)", line 36, in handle_rpc_call

return frappe.handler.handle()

^^^^^^^^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/[handler.py](http://handler.py/)", line 49, in handle

data = execute_cmd(cmd)

^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/[handler.py](http://handler.py/)", line 85, in execute_cmd

return [frappe.call](http://frappe.call/)(method, **frappe.form_dict)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/__init__.py", line 1768, in call

return fn(*args, **newargs)

^^^^^^^^^^^^^^^^^^^^

File "apps/frappe/frappe/utils/typing_[validations.py](http://validations.py/)", line 31, in wrapper

return func(*args, **kwargs)

^^^^^^^^^^^^^^^^^^^^^

File "apps/ecommerce_integrations/ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_[products.py](http://products.py/)", line 19, in get_shopify_products

shopify_products = fetch_all_products(from_)

^^^^^^^^^^^^^^^^^^^^^^^^^

File "apps/ecommerce_integrations/ecommerce_integrations/shopify/page/shopify_import_products/shopify_import_[products.py](http://products.py/)", line 29, in fetch_all_products

for product in collection:

TypeError: 'NoneType' object is not iterable

```

### Request Data

```

{

"type": "POST",

"args": {

"from_": null

},

"headers": {},

"error_handlers": {},

"url": "/api/method/ecommerce_[integrations.shopify.page](http://integrations.shopify.page/).shopify_import_products.shopify_import_products.get_shopify_products",

"request_id": "c826fd73-1b64-4eb2-ab2e-cb6bb83deea5"

}

```

### Response Data

```

{

"exception": "TypeError: 'NoneType' object is not iterable",

"exc_type": "TypeError",

"_exc_source": "ecommerce_integrations (app)"

}

**Comment by Karuppasamy923** [comment]
Hi @yasqueentyler ,

Kindly raise a support ticket so we can review the error logs in your instance. Please share the ticket ID here once.

Additionally, please ensure that the required Shopify scopes have been enabled in your Shopify store's Admin API access settings. This is essential for the integration to function correctly.

Regards,
Karuppasamy

**Comment by vinaymatlabInfotech** [comment]
![Image](https://github.com/user-attachments/assets/eec26352-73c0-484e-92c3-c43fad0d2f4e)

I'm also encountering the same error.
Has anyone found a way to resolve this?

Regards,
Vinay

**Comment by Karuppasamy923** [comment]
Hi @vinaymatlabInfotech,

Please ensure that your ERPNext and Shopify configurations are properly set up.
If you're using Frappe Cloud, kindly raise a support ticket so we can review the error logs on your instance.
Once done, please share the ticket ID here.

Regards,
Karuppasamy

**Comment by vinaymatlabInfotech** [comment]
@Karuppasamy923 The issue was resolved after clearing the cache properly. Once I added new items from the Shopify store, everything worked as expected in NexErp app. Thanks for replying.

**Comment by vinaymatlabInfotech** [comment]
In NextErp does have a amazon settlement report and functionality in a Ecommerce integration plugin?
