### ISSUE TITLE
Error Creating the Item in ERPNext and syncing it in Shopify

### ISSUE THREAD

**Issue by Payal-S-K** [frappe/ecommerce_integrations#336]
![Screenshot 2024-10-07 at 6 59 38 PM](https://github.com/user-attachments/assets/793a0973-4c10-429d-bd81-f163ae1928bb)

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1128, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/connection.py", line 37, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 376, in upload_erpnext_item
    update_default_variant_properties(
  File "apps/ecommerce_integrations/ecommerce_integrations/shopify/product.py", line 531, in update_default_variant_properties
    default_variant: Variant = shopify_product.variants[0]
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pyactiveresource/activeresource.py", line 917, in __getattr__
    raise AttributeError(name)
AttributeError: variants

**Comment by Karuppasamy923** [comment]
Hi @Payal-S-K,

Can you please share the exact versions of ERPNext and the e-commerce integration app you're using?

Also, if you're using Frappe Cloud, kindly raise a support ticket so we can review the error logs in your instance. Please share the ticket ID here once.

Additionally, please ensure that the required Shopify scopes have been enabled in your Shopify store's Admin API access settings. This is essential for the integration to function correctly.

Regards,
Karuppasamy

**Comment by flexGURU** [comment]
was this solved?
I am also facing the same issue?
