### ISSUE TITLE
Module ecommer_integrations not found after installation

### ISSUE THREAD

**Issue by Devil0815** [frappe/ecommerce_integrations#85]
Syncing items to Shopify works fine.
Also orders will be received from Shopify.
After receiving they are in queue. An error is from in background process.
Sync Stock is also not working.

Error in background process:
`
<function _migrate_items_to_ecommerce_item at 0x7f851691f3a0>Traceback (most recent call last):   File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 1008, in perform_job     self.prepare_job_execution(job)   File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 905, in prepare_job_execution     self.procline(msg.format(job.func_name, job.origin, time.time()))   File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.8/site-packages/rq/job.py", line 256, in func_name     self._deserialize_data()   File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.8/site-packages/rq/job.py", line 224, in _deserialize_data     self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data) ModuleNotFoundError: No module named 'ecommerce_integrations'
`
But the modules exist also on site?
![image](https://user-images.githubusercontent.com/91436922/134825109-c06dfa49-d25a-4228-84f0-b16b964a9877.png)

Hope anyone can fix this issue. I upgraded from erpnext_shopify app. Maybe this could make a difference?

**Comment by ankush** [comment]
Doesn't seem like it's installed properly. 😅  

Can you check if it's in installed packages?

```
cd /opt/bitnami/erpnext/frappe-bench
source env/bin/activate
pip freeze | grep ecommerce
```

> Also orders will be received from Shopify.

This could be from the old app.

**Comment by Devil0815** [comment]
Hi ankush,

I checked:

`bitnami@erp:~$` cd /opt/bitnami/erpnext/frappe-bench
bitnami@erp:/opt/bitnami/erpnext/frappe-bench$ source env/bin/activate
(env) bitnami@erp:/opt/bitnami/erpnext/frappe-bench$ pip freeze | grep ecommerce
-e git+https://github.com/frappe/ecommerce_integrations@dedaae7ca6197903b370997267c942b09186ce6a#egg=ecommerce_integrations`

but everything seems to be fine. Also there was absolutely no errors during installation. After installation system erpnext told me first to deactivate old shopify connector because ecommerce integrations was installed. Of course this I have done. I also checked the correct namings of modules and app.

I find also incoming Shopify API messages from test order:
![image](https://user-images.githubusercontent.com/91436922/134864867-3dab4fdc-e757-411a-ab15-f98ed8062907.png)
 
This settings are only done in new Shopify settings from ecommerce_integrations.

**Comment by Devil0815** [comment]
After setting up erpnext completely new (erpnext by bitnami) I installed ecommerce_integrations as it is described in your README. After this I still get the ModuleNotFoundError. 
Am I missing something? After checking I get the same result as I wrote in my last message.
