### ISSUE TITLE
Shopify Connector - Phone Number Extension Error

### ISSUE THREAD

**Issue by Trevor-66** [frappe/ecommerce_integrations#99]
I’ve successfully turned on the Shopify connector in ERPnext but I’m having an issue with orders that come in from Amazon through our Shopify store. As you may know, Amazon doesn’t release actual phone numbers on customer orders and instead gives an “anonymized” phone number with an extension number. This extension number is causing an error during the sync.

Error in Ecommerce Integration Log:
frappe.exceptions.InvalidPhoneNumberError: +X XXX-XXX-XXXX ext. XXXXX is not a valid Phone Number

**_Phone number removed for privacy_**

Does anyone have suggestions on how to correct this issue?

**Comment by Trevor-66** [comment]
Version: v13.12.1

**Method**
ecommerce_integrations.shopify.order.sync_sales_order

**Message**
+X XXX-XXX-XXXX ext. XXXXX is not a valid Phone Number

**Traceback (most recent call last):**
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/shopify/order.py", line 40, in sync_sales_order
    customer.sync_customer(customer=shopify_customer)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/shopify/customer.py", line 42, in sync_customer
    self.create_customer_contact(customer)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/shopify/customer.py", line 108, in create_customer_contact
    super().create_customer_contact(contact_fields)
  File "/home/frappe/frappe-bench/apps/ecommerce_integrations/ecommerce_integrations/controllers/customer.py", line 77, in create_customer_contact
    ).insert(ignore_mandatory=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 239, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 494, in _validate
    self._validate_data_fields()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 668, in _validate_data_fields
    frappe.utils.validate_phone_number(data, throw=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py", line 87, in validate_phone_number
    frappe.throw(frappe._("{0} is not a valid Phone Number").format(phone_number), frappe.InvalidPhoneNumberError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 438, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 417, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 371, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.InvalidPhoneNumberError: +X XXX-XXX-XXXX ext. XXXXX is not a valid Phone Number


**Request Data:**
{
    "admin_graphql_api_id": "gid://shopify/Order/XXXXXX",
    "app_id": 4989565,
    "billing_address": {
        "address1": "REMOVED",
        "address2": "",
        "city": "REMOVED",
        "company": "",
        "country": "REMOVED",
        "country_code": "REMOVED",
        "first_name": "REMOVED",
        "last_name": " REMOVED ",
        "latitude": REMOVED,
        "longitude": REMOVED,
        "name": "REMOVED",
        "phone": "+X XXX-XXX-XXXX ext. XXXXX",
        "province": " REMOVED ",
        "province_code": " REMOVED ",
        "zip": " REMOVED "
    },
    "browser_ip": null,
    "buyer_accepts_marketing": false,
    "cancel_reason": null,
    "cancelled_at": null,
    "cart_token": null,
    "checkout_id": null,
    "checkout_token": null,
    "closed_at": null,
    "confirmed": true,
    "contact_email": " REMOVED ",
    "created_at": "2021-10-08T02:12:25-05:00",
    "currency": "USD",
    "current_subtotal_price": " REMOVED ",
    "current_subtotal_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "current_total_discounts": "0.00",
    "current_total_discounts_set": {
        "presentment_money": {
            "amount": "0.00",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": "0.00",
            "currency_code": "USD"
        }
    },
    "current_total_duties_set": null,
    "current_total_price": " REMOVED ",
    "current_total_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "current_total_tax": "0.00",
    "current_total_tax_set": {
        "presentment_money": {
            "amount": "0.00",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": "0.00",
            "currency_code": "USD"
        }
    },
    "customer": {
        "accepts_marketing": false,
        "accepts_marketing_updated_at": "2021-10-08T02:12:24-05:00",
        "admin_graphql_api_id": "gid://shopify/Customer/ REMOVED ",
        "created_at": "2021-10-08T02:12:24-05:00",
        "currency": "USD",
        "default_address": {
            "address1": " REMOVED ",
            "address2": "",
            "city": " REMOVED ",
            "company": "",
            "country": " REMOVED ",
            "country_code": " REMOVED ",
            "country_name": " REMOVED ",
            "customer_id": REMOVED,
            "default": true,
            "first_name": " REMOVED ",
            "id": REMOVED,
            "last_name": " REMOVED ",
            "name": " REMOVED ",
            "phone": "+X XXX-XXX-XXXX ext. XXXXX",
            "province": " REMOVED ",
            "province_code": " REMOVED ",
            "zip": " REMOVED "
        },
        "email": " REMOVED ",
        "first_name": " REMOVED ",
        "id": REMOVED,
        "last_name": " REMOVED ",
        "last_order_id": REMOVED,
        "last_order_name": " REMOVED ",
        "marketing_opt_in_level": null,
        "multipass_identifier": null,
        "note": null,
        "orders_count": 1,
        "phone": null,
        "sms_marketing_consent": null,
        "state": "disabled",
        "tags": "Amazon",
        "tax_exempt": false,
        "tax_exemptions": [],
        "total_spent": " REMOVED ",
        "updated_at": "2021-10-08T02:12:26-05:00",
        "verified_email": true
    },
    "customer_locale": null,
    "device_id": null,
    "discount_applications": [],
    "discount_codes": [],
    "email": " REMOVED ",
    "estimated_taxes": false,
    "financial_status": "paid",
    "fulfillment_status": null,
    "fulfillments": [],
    "gateway": "amazon",
    "id": REMOVED,
    "landing_site": null,
    "landing_site_ref": null,
    "line_items": [
        {
            "admin_graphql_api_id": "gid://shopify/LineItem/ REMOVED ",
            "discount_allocations": [],
            "duties": [],
            "fulfillable_quantity": 1,
            "fulfillment_service": "manual",
            "fulfillment_status": null,
            "gift_card": false,
            "grams": 48,
            "id": REMOVED ,
            "name": " REMOVED ",
            "price": " REMOVED ",
            "price_set": {
                "presentment_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                }
            },
            "product_exists": true,
            "product_id": REMOVED,
            "properties": [
                {
                    "name": "ASIN",
                    "value": " REMOVED "
                }
            ],
            "quantity": 1,
            "requires_shipping": true,
            "sku": " REMOVED ",
            "tax_lines": [],
            "taxable": true,
            "title": " REMOVED ",
            "total_discount": "0.00",
            "total_discount_set": {
                "presentment_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                }
            },
            "variant_id": REMOVED,
            "variant_inventory_management": "shopify",
            "variant_title": " REMOVED ",
            "vendor": " REMOVED "
        },
        {
            "admin_graphql_api_id": "gid://shopify/LineItem/ REMOVED ",
            "discount_allocations": [],
            "duties": [],
            "fulfillable_quantity": 1,
            "fulfillment_service": "manual",
            "fulfillment_status": null,
            "gift_card": false,
            "grams": 73,
            "id": REMOVED,
            "name": " REMOVED ",
            "price": " REMOVED ",
            "price_set": {
                "presentment_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                }
            },
            "product_exists": true,
            "product_id": REMOVED,
            "properties": [
                {
                    "name": "ASIN",
                    "value": " REMOVED "
                }
            ],
            "quantity": 1,
            "requires_shipping": true,
            "sku": " REMOVED ",
            "tax_lines": [],
            "taxable": true,
            "title": " REMOVED ",
            "total_discount": "0.00",
            "total_discount_set": {
                "presentment_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                }
            },
            "variant_id": REMOVED,
            "variant_inventory_management": "shopify",
            "variant_title": null,
            "vendor": " REMOVED "
        },
        {
            "admin_graphql_api_id": "gid://shopify/LineItem/ REMOVED ",
            "discount_allocations": [],
            "duties": [],
            "fulfillable_quantity": 1,
            "fulfillment_service": "manual",
            "fulfillment_status": null,
            "gift_card": false,
            "grams": 49,
            "id": REMOVED,
            "name": " REMOVED ",
            "price": " REMOVED ",
            "price_set": {
                "presentment_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                }
            },
            "product_exists": true,
            "product_id": REMOVED,
            "properties": [
                {
                    "name": "ASIN",
                    "value": " REMOVED "
                }
            ],
            "quantity": 1,
            "requires_shipping": true,
            "sku": " REMOVED ",
            "tax_lines": [],
            "taxable": true,
            "title": " REMOVED ",
            "total_discount": "0.00",
            "total_discount_set": {
                "presentment_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": "0.00",
                    "currency_code": "USD"
                }
            },
            "variant_id": REMOVED,
            "variant_inventory_management": "shopify",
            "variant_title": null,
            "vendor": " REMOVED "
        }
    ],
    "location_id": null,
    "name": " REMOVED ",
    "note": null,
    "note_attributes": [
        {
            "name": "Amazon Order Id",
            "value": " REMOVED "
        },
        {
            "name": "Amazon Earliest Ship Date",
            "value": "2021-10-08T07:00:00.000Z"
        },
        {
            "name": "Amazon Earliest Delivery Date",
            "value": "2021-10-14T07:00:00.000Z"
        },
        {
            "name": "Amazon Latest Ship Date",
            "value": "2021-10-13T06:59:59.000Z"
        },
        {
            "name": "Amazon Latest Delivery Date",
            "value": "2021-10-20T06:59:59.000Z"
        },
        {
            "name": "Tax Reference",
            "value": "IOSS ,,"
        },
        {
            "name": " REMOVED ",
            "value": " REMOVED "
        }
    ],
    "number": REMOVED,
    "order_number": REMOVED,
    "order_status_url": " REMOVED ",
    "original_total_duties_set": null,
    "payment_gateway_names": [
        "amazon"
    ],
    "payment_terms": null,
    "phone": null,
    "presentment_currency": "USD",
    "processed_at": "2021-10-08T02:12:25-05:00",
    "processing_method": "",
    "reference": " REMOVED ",
    "referring_site": "https://www.amazon.com/dp/ REMOVED ",
    "refunds": [],
    "shipping_address": {
        "address1": " REMOVED ",
        "address2": "",
        "city": " REMOVED ",
        "company": "",
        "country": " REMOVED ",
        "country_code": " REMOVED ",
        "first_name": " REMOVED ",
        "last_name": " REMOVED ",
        "latitude": REMOVED,
        "longitude": REMOVED,
        "name": " REMOVED ",
        "phone": "+X XXX-XXX-XXXX ext. XXXXX",
        "province": " REMOVED ",
        "province_code": " REMOVED ",
        "zip": " REMOVED "
    },
    "shipping_lines": [
        {
            "carrier_identifier": null,
            "code": "AMZSTD",
            "delivery_category": null,
            "discount_allocations": [],
            "discounted_price": " REMOVED ",
            "discounted_price_set": {
                "presentment_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                }
            },
            "id": REMOVED,
            "phone": null,
            "price": " REMOVED ",
            "price_set": {
                "presentment_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                },
                "shop_money": {
                    "amount": " REMOVED ",
                    "currency_code": "USD"
                }
            },
            "requested_fulfillment_service_id": null,
            "source": "amazon",
            "tax_lines": [
                {
                    "channel_liable": null,
                    "price": "0.00",
                    "price_set": {
                        "presentment_money": {
                            "amount": "0.00",
                            "currency_code": "USD"
                        },
                        "shop_money": {
                            "amount": "0.00",
                            "currency_code": "USD"
                        }
                    },
                    "rate": 0.0,
                    "title": "Tax"
                }
            ],
            "title": "Amazon Standard"
        }
    ],
    "source_identifier": " REMOVED ",
    "source_name": "amazon",
    "source_url": null,
    "subtotal_price": " REMOVED ",
    "subtotal_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "tags": "A2AYPI2VAIR3R1, Amazon, Amazon-US, FBM",
    "tax_lines": [],
    "taxes_included": false,
    "test": false,
    "token": " REMOVED ",
    "total_discounts": "0.00",
    "total_discounts_set": {
        "presentment_money": {
            "amount": "0.00",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": "0.00",
            "currency_code": "USD"
        }
    },
    "total_line_items_price": " REMOVED ",
    "total_line_items_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "total_outstanding": "0.00",
    "total_price": " REMOVED ",
    "total_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "total_price_usd": " REMOVED ",
    "total_shipping_price_set": {
        "presentment_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": " REMOVED ",
            "currency_code": "USD"
        }
    },
    "total_tax": "0.00",
    "total_tax_set": {
        "presentment_money": {
            "amount": "0.00",
            "currency_code": "USD"
        },
        "shop_money": {
            "amount": "0.00",
            "currency_code": "USD"
        }
    },
    "total_tip_received": "0.00",
    "total_weight": 0,
    "updated_at": "2021-10-08T02:12:28-05:00",
    "user_id": null
}

**Comment by ankush** [comment]
Thanks, solution to this would be avoid validations. 

Will add this in next release.

**Comment by Trevor-66** [comment]
Thank you!
